# Mapping device types to their functional groups
device_groups:
  Authentication server: ["high_value"]
  Syslog server: ["high_value"]
  Web server: ["performance_affecting", "resilience_affected"]
  E-mail server: ["performance_affecting", "resilience_affected"]
  DNS server: ["performance_affecting", "resilience_affected"]
  SQL database: ["performance_affecting"]
  Employee computer: ["resilience_affected"]

# Device values are tuples of (C, I) where 
#   C is the compromise value representing the impact of this device ceasing operation
#   and I is the information value representing the impact of this device being infiltrated and the data from it being stolen
device_values:
  Printer: [0.05, 0.02]
  Employee computer: [0.05, 0.1]
  Printer server: [0.1, 0.2]
  DNS server: [0.2, 0.5]
  DHCP server: [0.1, 0.1]
  E-mail server: [7, 9]
  Web server: [10, 6]
  SQL database: [70, 100]
  Syslog server: [100, 100]
  Authentication server: [100, 100]
  Low value device: [0.001, 0.001]
