name: "Compositional_Experiment"

configs:
  - level: 0
    n_enclaves: 3
    constraints:
      max_isps: 2
      max_degree: 3
    sensitivities: [0.0, 0.5, 0.5]
    descriptors: ["std_devices", "nb_high_deg_nodes"]
    evaluation_metrics:
      attack_surface_exposure: 1.0
      trust_separation_score: 0.8
    generations: 100
    init_batch: 200
    batch_size: 100
    time_in_enclaves: 6
    n_simulations: 30

  - level: 1
    n_enclaves: 4
    constraints:
      max_isps: 1
      max_degree: 4
    sensitivities: [0.0, 0.7, 0.6, 0.3]
    descriptors: ["std_devices", "std_resilience", "std_web_facing"]
    evaluation_metrics:
      security_loss: 1.0
      performance_loss: 0.7
      resilience_loss: 0.6
    generations: 50
    init_batch: 10
    batch_size: 5
    time_in_enclaves: 6
    n_simulations: 7

  - level: 2
    n_enclaves: 4
    constraints:
      max_isps: 1
      max_degree: 3
    sensitivities: [0.1, 0.7, 0.9, 1.0]
    descriptors: ["std_devices", "std_high_value"]
    evaluation_metrics:
      security_loss: 1.0
      performance_loss: 0.5
      resilience_loss: 0.7
    generations: 50
    init_batch: 4
    batch_size: 4
    time_in_enclaves: 6
    n_simulations: 5