name: "Compositional"

configs:
  - level: 0
    n_enclaves: 3
    constraints:
      max_isps: 2
      max_degree: 3
    sensitivities: [0.2, 0.5, 0.8]
    descriptors: ["std_devices", "nb_high_deg_nodes", "std_web_facing"]
    evaluation_metrics:
      security_loss: 2.0
      performance_loss: 0.5
      resilience_loss: 0.5
      sensitivity_penalty: 0.5
      attack_surface_exposure: 2.0
      trust_separation_score: 1.0
    generations: 1000
    init_batch: 200
    batch_size: 100
    time_in_enclaves: 6
    n_simulations: 10

  - level: 1
    n_enclaves: 4
    constraints:
      max_isps: 1
      max_degree: 3
    sensitivities: [0.2, 0.2, 0.5, 0.5]
    descriptors: ["std_devices", "std_high_value"]
    evaluation_metrics:
      # security_loss: 1.0
      security_loss: 0.5
      resilience_loss: 0.6
    generations: 500
    init_batch: 100
    batch_size: 50
    time_in_enclaves: 4
    n_simulations: 10
