name: Exp1
n_enclaves: 5
init_batch: 400
batch_size: 400
generations: 30

constraints:
  max_isps: 2

n_devices: 
  Employee computer: 5
  Printer: 1
  Printer server: 1
  DNS server: 1
  DHCP server: 1
  E-mail server: 1
  Web server: 1
  SQL database: 1
  Syslog server: 1
  Authentication server: 1

descriptors: ["nb_high_deg_nodes", "std_devices"]
metric_weights: [1, 0, 0]
